In [1]:
import os
import sys
sys.path.insert(1,'/home/bwhiteak/ChaosESN/ESN_utils/')
from sklearn.metrics import mean_squared_error
import numpy as np
import rc_analysis as rca

In [17]:
# Get target and predictions
TRAINLENGTH = 14000 
TEST = 1000
SIGNUM = 0
# Load target signal
target_dir = '../Targets'
target_signals = ['Xsignal.npy',
                  'Zsignal.npy',
                  'MGsignal.npy',
                  'L3Dsignal.npy']
fpath = os.path.join(target_dir,target_signals[SIGNUM])
target = np.load(fpath, allow_pickle=True)
# Find range for NRMSE
MINMAX = np.max(target[:TRAINLENGTH+TEST]) - \
         np.min(target[:TRAINLENGTH+TEST]) 
print(f'Target {target_signals[SIGNUM]} shape is {target.shape}')

# Load in model predictions
model_dir = ['../X_Saved_Models',
             '../Z_Saved_Models',
             '../MG_Saved_Models',
             '../L3D_Saved_Models']
preds_dir = 'best/Preds'
sizes = [50,100,200,300,400,500,600,700,800,900,1000]
error_arr = np.zeros(len(sizes))

for i in range(len(sizes)):
    pred_str  = f'X_{sizes[i]}_Preds.npy'
    fppath = os.path.join(model_dir[SIGNUM],preds_dir,pred_str)
    prediction = np.squeeze(np.load(fppath, allow_pickle=True))
    if(SIGNUM != 3):
        nrmse = rca.NRMSE(target[TRAINLENGTH:TRAINLENGTH+TEST],
                          prediction[TRAINLENGTH:TRAINLENGTH+TEST],
                          MINMAX)
    else:
        nrmse = np.max(mean_squared_error(target[TRAINLENGTH:TRAINLENGTH+TEST],
                                   prediction[TRAINLENGTH:TRAINLENGTH+TEST],
                                   multioutput='raw_values',
                                   squared=False)/MINMAX) # Broadcasts over array dims
    print(f'NRMSE {nrmse:.2f}')
    error_arr[i] = nrmse

sigerr_str = ['./NBoutputs/mmX',
              './NBoutputs/mmZ',
              './NBoutputs/mmMG',
              './NBoutputs/mmL3D']

#np.save(sigerr_str[SIGNUM],error_arr)

Target Xsignal.npy shape is (16000,)
NRMSE 0.22
NRMSE 0.22
NRMSE 0.20
NRMSE 0.22
NRMSE 0.21
NRMSE 0.22
NRMSE 0.21
NRMSE 0.21
NRMSE 0.23
NRMSE 0.24
NRMSE 0.18


In [19]:
# sizes = [50,100,200,300,400,500,600,700,800,900,1000]
# X error
error_arr

array([0.21624743, 0.22193055, 0.20419782, 0.22429221, 0.20998573,
       0.21500659, 0.20992591, 0.21449938, 0.22536557, 0.23729644,
       0.18127746])

In [14]:
# Z error
error_arr

array([0.09164545, 0.09170231, 0.0864561 , 0.08789855, 0.08695369,
       0.07588717, 0.09108499, 0.08146496, 0.09152717, 0.07819455,
       0.10519117])

In [7]:
# L3D error
# error_arr

array([0.17215953, 0.1777001 , 0.18968838, 0.18230476, 0.18467843,
       0.15623653, 0.18381413, 0.17341621, 0.1374649 , 0.17331748,
       0.15091053])

In [10]:
# MG error
# error_arr

array([0.13606894, 0.12083855, 0.10271021, 0.08772637, 0.06516985,
       0.06536826, 0.08461943, 0.08421372, 0.06669223, 0.12072094,
       0.18890016])