In [14]:
import os
import sys
sys.path.insert(1,'/home/bwhiteak/ChaosESN/ESN_utils/')
from sklearn.metrics import mean_squared_error
import numpy as np
import rc_analysis as rca

In [17]:
# Get target and predictions
TRAINLENGTH = 14000 
TEST = 1000
SIGNUM = 2
# Load target signal
sig_str = ['X','Z','MG','L3D']
target_dir = '../Targets'
target_signals = ['Xsignal.npy',
                  'Zsignal.npy',
                  'MGsignal.npy',
                  'L3Dsignal.npy']
fpath = os.path.join(target_dir,target_signals[SIGNUM])
target = np.load(fpath, allow_pickle=True)
# Find range for NRMSE
MINMAX = np.max(target[:TRAINLENGTH+TEST]) - \
         np.min(target[:TRAINLENGTH+TEST]) 
print(f'Target {target_signals[SIGNUM]} shape is {target.shape}')

# Load in model predictions
model_dir = ['../X_Saved_Models',
             '../Z_Saved_Models',
             '../MG_Saved_Models',
             '../L3D_Saved_Models']
preds_dir = 'best/Preds'
sizes = [10,20,30,40,50,100,200,300,400,500,600,700,800,900,1000]
error_arr = np.zeros(len(sizes))

for i in range(len(sizes)):
    pred_str  = f'{sig_str[SIGNUM]}_{sizes[i]}_Preds.npy'
    fppath = os.path.join(model_dir[SIGNUM],preds_dir,pred_str)
    try:
        loaded_pred = np.load(fppath, allow_pickle=True)
    except:
        print('Failed on... ', fppath)
        continue
    prediction = np.squeeze(loaded_pred)
    if(SIGNUM != 3):
        nrmse = rca.NRMSE(target[TRAINLENGTH:TRAINLENGTH+TEST],
                          prediction[TRAINLENGTH:TRAINLENGTH+TEST],
                          MINMAX)
    else:
        nrmse = np.max(mean_squared_error(target[TRAINLENGTH:TRAINLENGTH+TEST],
                                   prediction[TRAINLENGTH:TRAINLENGTH+TEST],
                                   multioutput='raw_values',
                                   squared=False)/MINMAX) # Broadcasts over array dims
    print(f'Size {sizes[i]} NRMSE {nrmse:.2f}')
    error_arr[i] = nrmse

sigerr_str = ['./NBoutputs/mmX',
              './NBoutputs/mmZ',
              './NBoutputs/mmMG',
              './NBoutputs/mmL3D']

np.save(sigerr_str[SIGNUM],error_arr)

Target MGsignal.npy shape is (21000,)
Size 10 NRMSE 0.02
Size 20 NRMSE 0.03
Size 30 NRMSE 0.03
Size 40 NRMSE 0.03
Size 50 NRMSE 0.03
Size 100 NRMSE 0.03
Size 200 NRMSE 0.03
Size 300 NRMSE 0.03
Size 400 NRMSE 0.03
Size 500 NRMSE 0.03
Size 600 NRMSE 0.03
Size 700 NRMSE 0.03
Size 800 NRMSE 0.03
Size 900 NRMSE 0.03
Size 1000 NRMSE 0.03


In [6]:
# sizes = [50,100,200,300,400,500,600,700,800,900,1000]
# X error
# error_arr

array([0.22291012, 0.21130849, 0.21532181, 0.20592399, 0.21624743,
       0.22193055, 0.20419782, 0.22429221, 0.20998573, 0.21500659,
       0.20992591, 0.21449938, 0.22536557, 0.23729644, 0.18127746])

In [8]:
# Z error
# error_arr

array([0.        , 0.08740439, 0.07315155, 0.09099324, 0.09164545,
       0.09170231, 0.0864561 , 0.08789855, 0.08695369, 0.07588717,
       0.09108499, 0.08146496, 0.09152717, 0.07819455, 0.10519117])

In [13]:
# L3D error
# error_arr

array([0.20129788, 0.17380758, 0.18641412, 0.17410413, 0.17215953,
       0.1777001 , 0.18968838, 0.18230476, 0.18467843, 0.15623653,
       0.18381413, 0.17341621, 0.1374649 , 0.17331748, 0.15091053])

In [16]:
# MG error
# error_arr

array([0.02498525, 0.02907307, 0.02937277, 0.02947341, 0.02944896,
       0.02956742, 0.02874622, 0.02952656, 0.02958525, 0.029441  ,
       0.02961174, 0.02960487, 0.02962068, 0.02965921, 0.02959205])